# Generated by Django 5.2.6 on 2025-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_49578b_idx')],
            },
        ),
    ]
